"""architecture realignment 1 to 1 workflow mapping

Revision ID: 2994bb185290
Revises: ee17a6e77f73
Create Date: 2026-10-08 11:18:41.305989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2994bb185290'
down_revision: Union[str, Sequence[str], None] = 'ee17a6e77f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'part_number')
    op.drop_column('products', 'item_id')
    op.add_column('users', sa.Column('can_access_masters', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_production_mappings', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_consumption_norms', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_prd_planning', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_requirements', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_plant_workflow', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_purchase', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_purchase_orders', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_goods_receipts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index(op.f('uq_users_single_super_admin'), table_name='users', postgresql_where='(is_super_admin = true)')
    op.drop_column('users', 'can_create_po')
    op.drop_column('users', 'can_upload_grn')
    op.drop_column('users', 'can_view_reports')
    op.drop_column('users', 'can_edit_master_data')
    op.drop_column('users', 'can_approve_po')
    op.drop_column('users', 'can_view_planning')
    op.drop_column('users', 'can_confirm_demand')
    op.drop_column('users', 'can_run_calculations')
    op.drop_column('users', 'can_view_master_data')
    op.drop_column('users', 'can_approve_extra_demand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_approve_extra_demand', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_view_master_data', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_run_calculations', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_confirm_demand', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_view_planning', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_approve_po', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_edit_master_data', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_view_reports', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_upload_grn', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_create_po', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('uq_users_single_super_admin'), 'users', ['is_super_admin'], unique=True, postgresql_where='(is_super_admin = true)')
    op.drop_column('users', 'can_access_goods_receipts')
    op.drop_column('users', 'can_access_purchase_orders')
    op.drop_column('users', 'can_access_purchase')
    op.drop_column('users', 'can_access_inventory')
    op.drop_column('users', 'can_access_plant_workflow')
    op.drop_column('users', 'can_access_requirements')
    op.drop_column('users', 'can_access_prd_planning')
    op.drop_column('users', 'can_access_consumption_norms')
    op.drop_column('users', 'can_access_production_mappings')
    op.drop_column('users', 'can_access_masters')
    op.add_column('products', sa.Column('item_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('part_number', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
