"""Add granular permission matrix

Revision ID: 9b191a5582df
Revises: 0019_prd_workspace
Create Date: 2026-10-07 14:33:52.541339
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b191a5582df'
down_revision: Union[str, Sequence[str], None] = '0019_prd_workspace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goods_receipt_records_is_deleted'), table_name='goods_receipt_records')
    op.drop_index(op.f('ix_prd_records_is_deleted'), table_name='prd_records')
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_view_master_data', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_edit_master_data', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_view_planning', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_run_calculations', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_confirm_demand', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_approve_extra_demand', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_create_po', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_approve_po', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_upload_grn', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_view_reports', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_plant_1', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_plant_2', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_plant_3', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_plant_4', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_access_plant_5', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_access_plant_5')
    op.drop_column('users', 'can_access_plant_4')
    op.drop_column('users', 'can_access_plant_3')
    op.drop_column('users', 'can_access_plant_2')
    op.drop_column('users', 'can_access_plant_1')
    op.drop_column('users', 'can_view_reports')
    op.drop_column('users', 'can_upload_grn')
    op.drop_column('users', 'can_approve_po')
    op.drop_column('users', 'can_create_po')
    op.drop_column('users', 'can_approve_extra_demand')
    op.drop_column('users', 'can_confirm_demand')
    op.drop_column('users', 'can_run_calculations')
    op.drop_column('users', 'can_view_planning')
    op.drop_column('users', 'can_edit_master_data')
    op.drop_column('users', 'can_view_master_data')
    op.drop_column('users', 'is_super_admin')
    op.create_index(op.f('ix_prd_records_is_deleted'), 'prd_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_goods_receipt_records_is_deleted'), 'goods_receipt_records', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
