"""add plant process route masters

Revision ID: acfaead772de
Revises: 0002_auth_rbac
Create Date: 2026-10-01 14:11:38.541531
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acfaead772de'
down_revision: Union[str, Sequence[str], None] = '0002_auth_rbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants'))
    )
    op.create_index(op.f('ix_plants_name'), 'plants', ['name'], unique=True)
    op.create_table('processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes'))
    )
    op.create_index(op.f('ix_processes_name'), 'processes', ['name'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=True)
    op.create_table('route_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_route_steps_process_id_processes')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_steps_route_id_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_steps'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_steps')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_processes_name'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_plants_name'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
