"""add employee id and name

Revision ID: ee17a6e77f73
Revises: 9b191a5582df
Create Date: 2026-10-07 15:59:02.871572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee17a6e77f73'
down_revision: Union[str, Sequence[str], None] = '9b191a5582df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_users_employee_id'), 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_employee_id'), 'users', type_='unique')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
